site_name: nightWolf
site_favicon: 'img/favi.png'
site_url: https://www.nightwolf.in

theme:
    name: mkdocs 
    nav_style: dark
    logo: wolf.png
    analytics:
      gtag: G-8QN4YRWY1N

markdown_extensions:
    - toc:
        permalink: ""
    - markdown_include.include:
    - attr_list:

# Copyright
copyright: 'Copyright &copy; 2022 nightWolf'

nav:
    - Home: index.md
    - Linux-Performance: nightwolf-cotribution/performance.md
    - Interview-Prep:
        - Linux Interview Questions:
           - 'Linux Interview Questions for Freshers': 'nightwolf-cotribution/linux_basic.md'
           - 'Linux Interview Questions for Freshers - 2': 'nightwolf-cotribution/linux_interview_questions_for_freshers.md'
           - 'Linux Interview Questions for Freshers and Experienced - L1': 'nightwolf-cotribution/linux_L1.md'
           - 'Linux Interview Questions for Experienced Linux Admins - L2': 'nightwolf-cotribution/linux_L2.md'
           - 'Advanced Linux Interview Questions for Experienced Admins - L3': 'nightwolf-cotribution/linux_L3.md'
           - 'Solved list of Linux interview Questions': 'nightwolf-cotribution/linux_questionairs.md'
        - Shell-Scripting Interview Questions: 'nightwolf-cotribution/shell_scripting_interview_questions.md'
        - OS Networking Interview Questions: 'nightwolf-cotribution/network.md'
        - DevOps Interview Questions:
            - DevOps Interview Questions for Freshers and Experienced: 'nightwolf-cotribution/devops_interview_questions.md'
            - DevOps Interview Questions for Freshers and Experienced-2: 'nightwolf-cotribution/devops_interview_questions-2.md'
        - GIT Interview Questions: 'nightwolf-cotribution/git.md'
        - Jenkins Interview Questions: 'nightwolf-cotribution/jenkins.md'
        - Docker Interview Questions: 'nightwolf-cotribution/docker_interview_questions.md'
        - Kubernetes Interview Questions: 'nightwolf-cotribution/kubernetes_interview_questions.md'
        - Ansible Interview Questions: 'nightwolf-cotribution/ansible_interview_questions.md'
        - Java/OOPs Interview Questions:
            - Java/OOPs Interview Questions: 'nightwolf-cotribution/java_interview_questions.md'
            - Java/OOPs Interview Questions-2: 'nightwolf-cotribution/java_interview_questions-2.md'
        - Terraform Interview Questions:  
            - Terraform Interview Questions and Answers- 1st: 'nightwolf-cotribution/terraform_interview_question.md'
            - Terraform Interview Questions and Answers- 2nd: 'nightwolf-cotribution/terraform_interview_question-2.md'
            - Terraform Interview Questions and Answers- 3rd: 'nightwolf-cotribution/terraform_interview_question-3.md'
        - Google Cloud Certification Practice Questions:
            - GCP ACE Practice Questions-1: 'nightwolf-cotribution/gcp-ace-1.md'
            - GCP ACE Practice Questions-2: 'nightwolf-cotribution/gcp-ace-2.md'
            - GCP ACE Practice Questions-3: 'nightwolf-cotribution/gcp-ace-3.md'
        - AWS Interview Questions: 
            - AWS Certified SysOps Administrator Questions- 1st: 'nightwolf-cotribution/aws.md'
            - AWS Certified SysOps Administrator Questions- 2nd: 'nightwolf-cotribution/aws-2.md'
            - AWS Interview Questions- 1st: 'nightwolf-cotribution/aws-3.md'
            - AWS Interview Questions- 2nd: 'nightwolf-cotribution/aws-4.md'
        - Manual Testing/QA Interview Questions: 'nightwolf-cotribution/manual_testing_interview_questions.md'
        - DBMS Interview Questions and Answers: 'nightwolf-cotribution/dbms_interview_questions.md'
        - Azure Interview Questions: 'nightwolf-cotribution/azure.pdf'
        - Managerial Interview Questions: 'nightwolf-cotribution/managerial_interview_questions.md'
    - Cheatsheets:
         - Kubernetes CheatSheet: nightwolf-cotribution/kubernetes_cheatsheet.md
         - GIT CheatSheet: nightwolf-cotribution/git_cheatsheet.md
         - Linux YUM CheatSheet: nightwolf-cotribution/yum_cheatsheet.pdf
         - Yum vs APT cheatsheet: nightwolf-cotribution/yum_vs_apt.md
         - gcloud commands Cheatsheet: gcloud_cheatsheet.md
         - TLS Version key differences: nightwolf-cotribution/TLS-Difference.md
    - Technical:
         - Linux: linux.md
         - Network: network.md
         - Database: db/
         - Cloud: 
           - Service Comparison between GCP, AWS, Azure: cloud-comp.md
         - Group for Jobs postings: https://www.linkedin.com/groups/8982092/

    - Articles:
        - What is Artificial Intelligence(AI) ?: articles/ai_intro.md
        - Unleashing the Power of Artificial Intelligence: articles/ai_trends.md
        - What is Machine Learning ?: articles/machine_learning_intro.md
        - What is Neural Network ?: articles/neural_networks.md
        - What is Internet of Things (IoT) ?: articles/iot.md
        - What is Natural Language Processing (NLP) ?: articles/natural_language_processing.md
        - What is Robotics and Automation ?: articles/robotics_automation.md

