site_name: nightWolf
site_url: https://www.nightwolf.in/
site_favicon: 'img/favi.png'
google_analytics: ['UA-220186946-1', 'nightwolf.in']

theme:
    name: mkdocs 
    nav_style: dark
    logo: wolf.png

markdown_extensions:
    - toc:
        permalink: ""

# Copyright
copyright: 'Copyright &copy; 2022 nightWolf'

nav:
    - Home: index.md
    - Linux-Performance: nightwolf-cotribution/performance.md
    - Interview-Prep:
        - Linux Interview Questions:
           - 'Linux Interview Questions for Freshers': 'nightwolf-cotribution/linux_basic.md'
           - 'Linux Interview Questions for Freshers - 2': 'nightwolf-cotribution/linux_interview_questions_for_freshers.md'
           - 'Linux Interview Questions for Freshers and Experienced - L1': 'nightwolf-cotribution/linux_L1.md'
           - 'Linux Interview Questions for Experienced Linux Admins - L2': 'nightwolf-cotribution/linux_L2.md'
           - 'Advanced Linux Interview Questions for Experienced Admins - L3': 'nightwolf-cotribution/linux_L3.md'
           - 'Solved list of Linux interview Questions': 'nightwolf-cotribution/linux_questionairs.md'
        - DevOps Interview Questions:
            - DevOps Interview Questions for Freshers and Experienced: 'nightwolf-cotribution/devops_interview_questions.md'
            - DevOps Interview Questions for Freshers and Experienced - 2 : 'nightwolf-cotribution/devops_interview_questions-2.md'
            - GIT Interview Questions: 'nightwolf-cotribution/git.md'
            - Jenkins Interview Questions: 'nightwolf-cotribution/jenkins.md'
            - Docker Interview Questions: 'nightwolf-cotribution/docker_interview_questions.md'
        - OS Networking Interview Questions: 'nightwolf-cotribution/network.md'
        - AWS Interview Questions: 'nightwolf-cotribution/aws.md'
        - Azure Interview Questions: 'nightwolf-cotribution/azure.pdf'
    - Cheatsheets:
         - Kubernetes CheatSheet: nightwolf-cotribution/kubernetes_cheatsheet.md
         - GIT CheatSheet: nightwolf-cotribution/git_cheatsheet.md
         - Linux YUM CheatSheet: nightwolf-cotribution/yum_cheatsheet.pdf
    - Technical:
         - Linux: linux.md
         - Network: network.md
         - Database: db/
    - Discussions: https://talks.nightwolf.in


extra:
  analytics:
    provider: google
    property: UA-220186946-1 
