site_name: nightWolf
site_url: https://www.nightwolf.in/
site_favicon: 'img/favi.png'
google_analytics: ['G-DSYZJFJTEB', 'nightwolf.in']

theme:
    name: mkdocs 
    nav_style: dark
    logo: wolf.png

markdown_extensions:
    - toc:
        permalink: ""

# Copyright
copyright: 'Copyright &copy; 2022 nightWolf'

nav:
    - Home: index.md
    - Performance-Troubleshooting: nightwolf-cotribution/performance.md
    - Interview-Preparation: interview.md
    - Linux: linux.md
    - Network: nightwolf-cotribution/network
    - Database: db/

#        - 'Linux + OS Interview Questions': 'linux_questionairs.md'
#        - 'Networking Interview Questions': 'network.md'

extra:
  analytics:
    provider: google
    property: G-DSYZJFJTEB
