site_name: nightWolf
site_url: https://www.nightwolf.in/
site_favicon: 'img/favi.png'
theme:
    name: mkdocs 
    nav_style: dark
    logo: wolf.png

# Copyright
copyright: 'Copyright &copy; 2022 nightWolf'

nav:
    - Home: index.md
    - Performance-Troubleshooting: nightwolf-cotribution/performance.md
    - Interview-Preparation: interview.md
    - Linux: linux.md
    - Network: network.md
    - Database: db.md

#        - 'Linux + OS Interview Questions': 'linux_questionairs.md'
#        - 'Networking Interview Questions': 'network.md'


