site_name: nightWolf
site_url: https://www.nightwolf.in/
site_favicon: 'img/favi.png'
google_analytics: ['UA-220186946-1', 'nightwolf.in']

theme:
    name: mkdocs 
    nav_style: dark
    logo: wolf.png

markdown_extensions:
    - toc:
        permalink: ""

# Copyright
copyright: 'Copyright &copy; 2022 nightWolf'

nav:
    - Home: index.md
    - Performance-Troubleshooting: nightwolf-cotribution/performance.md
    - Interview-Prep:
        - Linux Interview Questions:
           - 'Linux General Questions': 'nightwolf-cotribution/linux_basic.md'
           - 'Linux L1 interview Questions': 'nightwolf-cotribution/linux_L1.md'
           - 'Linux L2 interview Questions': 'nightwolf-cotribution/linux_L2.md'
           - 'Linux L3 interview Questions': 'nightwolf-cotribution/linux_L3.md'
        - OS Networking Interview Questions: 'nightwolf-cotribution/network.md'
        - AWS Interview Questions: 'nightwolf-cotribution/aws.md'
        - GIT Interview Questions: 'nightwolf-cotribution/git.md'
        - Jenkins Interview Questions: 'nightwolf-cotribution/jenkins.md'     
        - Azure Interview Questions: 'nightwolf-cotribution/azure.pdf'
    - Linux: linux.md
    - Network: nightwolf-cotribution/network
    - Database: db/
    - Discussions: https://talks.nightwolf.in


extra:
  analytics:
    provider: google
    property: UA-220186946-1 
